### ISSUE TITLE
permalink in anchors shouldn't be parsed by TOC helper

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo-renderer-markdown-it#102]
## Issue / current behavior

Currently permalinks are added as a link inside the title, for example:

```html
<h3 id="create-a-new-post">
  <a class="header-anchor" href="#create-a-new-post">#</a>
  Create a new post
</h3>
```

This will produce something like:

![image](https://user-images.githubusercontent.com/16578570/71783535-58fb3e00-2fe8-11ea-84a5-e0db4f597452.png)

The problem is the permalink symbol will be part of the title.

So when you use, for example, the `toc` helper, the permalink symbol will be added in the title too.

![image](https://user-images.githubusercontent.com/16578570/71783548-8ba53680-2fe8-11ea-8ee2-d5080bff7c95.png)

```html
<ol class="toc">
    <li class="toc-item toc-level-2"><a class="toc-link" href="#quick-start"><span class="toc-number">1.</span> <span class="toc-text">#Quick Start</span></a>
        <ol class="toc-child">
            <li class="toc-item toc-level-3"><a class="toc-link" href="#create-a-new-post"><span class="toc-number">1.1.</span> <span class="toc-text">#Create a new post</span></a></li>
            <li class="toc-item toc-level-3"><a class="toc-link" href="#run-server"><span class="toc-number">1.2.</span> <span class="toc-text">#Run server</span></a></li>
            <li class="toc-item toc-level-3"><a class="toc-link" href="#generate-static-files"><span class="toc-number">1.3.</span> <span class="toc-text">#Generate static files</span></a></li>
            <li class="toc-item toc-level-3"><a class="toc-link" href="#deploy-to-remote-sites"><span class="toc-number">1.4.</span> <span class="toc-text">#Deploy to remote sites</span></a></li>
        </ol>
    </li>
</ol>
```

## Idea of fixing / workaround

My workaround was to set a null symbol `permalinkSymbol: ''` and to add some css (sass here):

```sass
h1,h2,h3,h4,h5,h6 
  a::before
    content: '#'
```

So this display the same and is still clickable but there is no more content in the title.

Same look

![image](https://user-images.githubusercontent.com/16578570/71783635-da070500-2fe9-11ea-90c3-d96dd4deaeb2.png)

No more issue with the toc helper

![image](https://user-images.githubusercontent.com/16578570/71783637-e5f2c700-2fe9-11ea-9513-bb06dc94964f.png)

![image](https://user-images.githubusercontent.com/16578570/71783659-3ff38c80-2fea-11ea-907c-60aec254c77a.png)

But I think it can't be fixed like this because this plugin only generates html, no css.

## Alternative idea

Fix the toc helper to select only text content and not other sub-elements like links.

https://github.com/hexojs/hexo/issues/4057

## Environment

Happening with both hexo: 4.2.0 and hexo: 4.1.1

**Comment by stevenjoezhang** [comment]
See also https://github.com/theme-next/hexo-theme-next/issues/877

**Comment by curbengh** [comment]
> Currently permalinks are added as a link inside the title

I assume you enabled `permalink`? It's disabled by default in v4 (of this plugin).

``` diff
markdown:
  anchors:
    permalink: true
```

> The problem is the permalink symbol will be part of the title.

What is the expected behavior?

Show permalink symbol in heading, but not in toc?

**Comment by noraj** [comment]
> I assume you enabled `permalink`? It's disabled by default in v4 (of this plugin).

Yeah I enabled `permalink` because I want them.

> What is the expected behavior?
>
> Show permalink symbol in heading, but not in toc?

Exactly. I see you confirmed the issue is coming from cheerio (https://github.com/hexojs/hexo-util/issues/174#issuecomment-573373405).
