### ISSUE TITLE
渲染 选择框 失败问题！

### ISSUE THREAD

**Issue by constown** [hexojs/hexo-renderer-markdown-it#114]
如图：
我在typora中预览效果：
![image](https://user-images.githubusercontent.com/50108901/82427228-5f7fe300-9abb-11ea-85f5-4103d246c681.png)
实际渲染效果：
![image](https://user-images.githubusercontent.com/50108901/82427304-81796580-9abb-11ea-9b53-bdd118d7afa8.png)

使用原生插件渲染效果应该大概是这样：
![image](https://user-images.githubusercontent.com/50108901/82427540-d3ba8680-9abb-11ea-9ffd-68c77ba5d759.png)

**Comment by jeffery0628** [comment]
你解决这个问题了吗，我也遇到了同样的问题

**Comment by jeffery0628** [comment]
我解决了：npm install markdown-it-task-lists ，然后把 markdown-it-task-lists  添加到插件就好了。

**Comment by constown** [comment]
我使用了另外一个插件！

hexo-filter-emoji

**Comment by constown** [comment]
@jeffery0628 我使用了另外一个插件！
```
 hexo-filter-emoji
```
