### ISSUE TITLE
「linkify」How to prevent "test.it" from turning into a link, while turning "https://test.it" into a link?

### ISSUE THREAD

**Issue by forliuyifei** [hexojs/hexo-renderer-markdown-it#138]
![image](https://user-images.githubusercontent.com/53306807/98437342-5394e580-211c-11eb-93c2-e492eb8d1320.png)

👆 It's embarrassing.  
Is there any advanced setting about **linkify** ?

**Comment by SukkaW** [comment]
Technically `here.it` and `test.it` are both valid domains. `.it` is the ccTLD of Itali.

Also, in English, there should be a space after `.`:

```
I am here.It is 8:00
```

should be

```
I am here. It is 8:00
```
