### ISSUE TITLE
postAsset config in markdown-it render

### ISSUE THREAD

**Issue by fengkx** [hexojs/hexo-renderer-markdown-it#140]
I want to implement [postAsset](https://github.com/hexojs/hexo-renderer-marked/pull/159) in markdown-it render.

I try implement it with a filter bind to `markdown-it:renderer`. But later I can't find a way to access `data.path` like [here](https://github.com/hexojs/hexo-renderer-marked/blob/9200d9913e8f68ffdb2470c82709d40b7a5e96cb/lib/renderer.js#L127) in the filter.

Is there any way to access the post currently render in `markdown-it:render` filter?

Maybe add an args when execute the filter may help?
```js
this.execFilterSync('markdown-it:renderer', parser, { context: this , args: [data.path]});
```

**Comment by SukkaW** [comment]
See https://github.com/hexojs/hexo-renderer-marked/pull/173

**Comment by fengkx** [comment]
The problem is I cannot access data https://github.com/curbengh/hexo-renderer-marked/blob/d5c2ed1ec65fa400def711287e40d85befe405dc/lib/renderer.js#L227 in the filter @SukkaW

**Comment by fengkx** [comment]
Make a pull request about this #141
