### ISSUE TITLE
Not support todo list

### ISSUE THREAD

**Issue by cxplay** [hexojs/hexo-renderer-markdown-it#151]
![image](https://user-images.githubusercontent.com/62034099/131236454-17b85c44-07d1-4151-83f1-554caebe0f62.png)

Like this:

```Markdown
 - [ ] Todo list
 - [x] Todo list
 - [ ] ?
```

So why not support it?

https://github.github.com/gfm/#task-list-items-extension%2D

**Comment by tomap** [comment]
https://github.com/hexojs/hexo-renderer-markdown-it/pull/28

https://github.com/hexojs/hexo-renderer-markdown-it/issues/136

See those links to handle plugin that will display checkboxes

**Comment by renbaoshuo** [comment]
您可以通过安装 `markdown-it-task-lists` 插件解决此问题。
