### ISSUE TITLE
emoji support

### ISSUE THREAD

**Issue by wayou** [hexojs/hexo-renderer-markdown-it#17]
any plan for emoji support like github flavored markdown?

**Comment by celsomiranda** [comment]
Emoji support does not depend solely on the renderer.

You would have to use an icon font or something like that to benefit from emoji support.

**Comment by wayou** [comment]
maybe can integrate this [markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji) to make the tenderer does so

**Comment by noraj** [comment]
[hexo-renderer-markdown-it-plus](https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus) theoretically does it.

**Comment by stevenjoezhang** [comment]
Here is a plugin: https://github.com/hexo-next/hexo-filter-emoji

**Comment by noraj** [comment]
I guess this issue can be closed
