### ISSUE TITLE
Markdown italics not rendering

### ISSUE THREAD

**Issue by lorezyra** [hexojs/hexo-renderer-markdown-it#179]
Am I missing something? 

When I use ``` make this _word_ italic``` it does _not_ render with the ```<i>``` (```<em>```) HTML code. Seems like it's completely ignored. However bold text renders without issue.

https://github.com/lorezyra/blog.RichieBartlett.com

**Comment by tomap** [comment]
Can you add a link to the specific markdown file with the issue?

**Comment by lorezyra** [comment]
_All_ my markdown files have this issue. But here's an example file to review:
https://github.com/lorezyra/blog.RichieBartlett.com/blob/Production/source/_posts/Money_%E7%B5%8C%E6%B8%88/100-000-You-Absolutely-Can-Be-Set-For-Life.md

Rendered on website:
https://blog.richiebartlett.com/2022/0314/Money_%E7%B5%8C%E6%B8%88/100-000-You-Absolutely-Can-Be-Set-For-Life.html

**Comment by lorezyra** [comment]
Sometimes, I'm an idiot... I found the problem... it's in my CSS rules. The source code shows the correct HTML. But somewhere, the CSS is overriding it. Apologies for taking your time.
