### ISSUE TITLE
Following the latest GFM specification

### ISSUE THREAD

**Issue by zhang-stephen** [hexojs/hexo-renderer-markdown-it#219]
### Check List

- [X] I have already read README.
- [X] I have already searched existing issues.
- [X] I have already searched existing pull requrests.

### Feature Request

Follow the latest GFM specification for preset `GFM` or `default`, e.g. add support for [Alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).

screenshots here(rendered):
![](https://docs.github.com/assets/cb-24696/mw-1440/images/help/writing/alerts-rendered.webp)

I think it could be more useful to express more information.

**Comment by SukkaW** [comment]
As the name implies, `hexo-renderer-markdown-it` is based on `markdown-it`: https://github.com/markdown-it/markdown-it

Please submit a feature request there instead.
