### ISSUE TITLE
Support for CSS classes in markdown

### ISSUE THREAD

**Issue by m3t** [hexojs/hexo-renderer-markdown-it#24]
Maybe you would like to consider adding the plugin [`markdown-it-classy`](https://github.com/andrey-p/markdown-it-classy).
On the face of it, the plugin does what it's supposed to in my hexo installation.

Example:

``` md
- so
- are
- ul tags
{classy}
```

converts to

``` html
<ul class="classy">
    <li>so</li>
    <li>are</li>
    <li>ul tags</li>
</ul>
```

**Comment by celsomiranda** [comment]
I don't really have the time right now to implement new stuff. :disappointed: I barely have the time to properly maintain it. :/

If someone else would do it, and the proper tests, I'll merge though.

**Comment by m3t** [comment]
I'm sorry for that,
but hopefully there's time to have a look at
#27

**Comment by celsomiranda** [comment]
I've been trying to fix the remaining bug, but I've not been able to do it. Would prefer to merge when all is good.

**Comment by noraj1337** [comment]
This is not supported by markdown so whit a markdown renderer will do that ?

**Comment by stevenjoezhang** [comment]
Closing as not considered part of the current focus.
