### ISSUE TITLE
Cannot render headings with ids?

### ISSUE THREAD

**Issue by pujiaxun** [hexojs/hexo-renderer-markdown-it#40]
This renderer cannot generate ids in headings because of Markdown-it plugin not implement it.
So I tried a solution
Just use a plugin `markdown-it-named-headings`

``` bash
npm install markdown-it-named-headings --save
```

And then add one line to render it with this plugin.

``` js
parser.use(require('markdown-it-named-headings'))
```

Just like this.

``` js
'use strict';

module.exports = function (data, options) {
  var MdIt = require('markdown-it');
  var cfg = this.config.markdown;
  var opt = (cfg) ? cfg : 'default';
  var parser = (opt === 'default' || opt === 'commonmark' || opt === 'zero') ?
    new MdIt(opt) :
    new MdIt(opt.render);

  parser.use(require('markdown-it-named-headings'))

 if (opt.plugins) {
    parser = opt.plugins.reduce(function (parser, pugs) {
      return parser.use(require(pugs));
    }, parser);
  }

  if (opt.anchors) {
    parser = parser.use(require('./anchors'), opt.anchors);
  }

  return parser.render(data.text);
};

```

Could I make a PR for this?

**Comment by khiav223577** [comment]
Thanks. It works!

**Comment by onlyfly34** [comment]
Is this merged into the project? I had the same issues but reinstalling hexo solved my problem without adding `parser.use(require('markdown-it-named-headings'))`

**Comment by HanchengZhao** [comment]
Hi, I wonder what else do you need to do after adding this line? I still have the problem after doing that. Thanks

**Comment by pujiaxun** [comment]
I think that’s all I did. Maybe dependencies had updated?

**Comment by pujiaxun** [comment]
@HanchengZhao  Maybe you can reference this issue. If it doesn't work, I cannot solve it neither.

https://github.com/pujiaxun/pujiaxun.github.io/issues/1

**Comment by HanchengZhao** [comment]
@pujiaxun Thanks for the comment. My issue actually has something to do with 'hexo-toc' package. For those who might have the same problem, check out https://github.com/YenYuHsuan/hexo-theme-beantech/issues/11

**Comment by noraj** [comment]
hexo-renderer-markdown-it is not compatible with hexo-toc yet even if hexo-toc claims it.

See https://github.com/bubkoo/hexo-toc/issues/20

**Comment by noraj** [comment]
Is this issue still up to date or it can be closed ?

**Comment by noraj** [comment]
@pujiaxun hexo-renderer-markdown-it works perfectly, it's hexo-toc that is a mess.
