### ISSUE TITLE
Not work for "read more" in next theme

### ISSUE THREAD

**Issue by RickDYang** [hexojs/hexo-renderer-markdown-it#41]
Next theme has a feature to add \<!--more--\> in archicle to generate a "read more" link. But it did not work in hexo-renderer-markdown-it but work well on hexo-renderer-marked.
See details in http://theme-next.iissnan.com/faqs.html

**Comment by NoahDragon** [comment]
Set the html config to true could be a solution.
https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration#html

**Comment by dofine** [comment]
Still not working for me here.
