### ISSUE TITLE
How to pass parameters to the 'markdown-it-checkbox' plugin?

### ISSUE THREAD

**Issue by maboloshi** [hexojs/hexo-renderer-markdown-it#42]
[markdown-it-checkbox](https://github.com/mcecot/markdown-it-checkbox) plugin has three parameters. How to pass parameters to the 'markdown-it-checkbox' plugin ? How to set the _ config.yml file?

**Comment by yfwz100** [comment]
I encountered this problem too. You may find #28 helpful. However, it hasn't released yet in the npm registry. You have to merge the patch yourself.

**Comment by sappy5678** [comment]
maybe you can use this command to install it directly from github
`npm install git+https://github.com/hexojs/hexo-renderer-markdown-it.git --save`

**Comment by stevenjoezhang** [comment]
New version v4.0.0 & 4.1.0 released on npm
