### ISSUE TITLE
Treat html comments as inline html

### ISSUE THREAD

**Issue by dazinator** [hexojs/hexo-renderer-markdown-it#43]
It seems html comments are currently html encoded. Please can these be left as inline html? For motivation behind this, please see https://github.com/hexojs/hexo/issues/2316

I think #41 is also down to this.

**Comment by NoahDragon** [comment]
I think you could set the html config to true:
https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration#html

**Comment by noraj1337** [comment]
You can close this issue I think.
