### ISSUE TITLE
Render problem with image inside a link (linked image)

### ISSUE THREAD

**Issue by noraj1337** [hexojs/hexo-renderer-markdown-it#46]
Image inside a link (linked image) is not rendered properly.

Markdown:

```markdown
[![](https://ctftime.org/static/images/CTFTIME-flat-logo-true.png)](https://ctftime.org/user/16344)
```

Rendered with hexo render markdown it:

```html
<a href="https://ctftime.org/user/16344">
    <a href="https://ctftime.org/static/images/CTFTIME-flat-logo-true.png" title="">
        <img src="https://ctftime.org/static/images/CTFTIME-flat-logo-true.png" alt="">
    </a>
</a>
```

Rendered with [official markdown previewer](https://daringfireball.net/projects/markdown/dingus):

```html
<a href="https://ctftime.org/user/16344">
    <img src="https://ctftime.org/static/images/CTFTIME-flat-logo-true.png" alt="" title="">
</a>
```

The fun fact is that [markdown-it demo](https://markdown-it.github.io/) render it well but hexo-renderer-markdown-it not.

**Comment by NoahDragon** [comment]
Could you please post the plugins you have installed and the theme is using?

**Comment by noraj1337** [comment]
+ Theme: https://github.com/ppoffice/hexo-theme-hueman
+ My website: https://rawsec.ml/
+ My website source: https://gitlab.com/noraj/Rawsec-website
+ Plugins: https://gitlab.com/noraj/Rawsec-website/blob/master/package.json

**Comment by NoahDragon** [comment]
I think it may cause by the fancybox.  Could you please turn it off, and see if there is a difference?

**Comment by noraj1337** [comment]
@NoahDragon . I tested, changed nothing.

**Comment by noraj1337** [comment]
I also made an fresh default hexo site with `hexo init` uninstalled `marked` and install `markdown-it`, desactivated the fancybox and the problem is still the same. So this is really a problem of the hexo renderer.

**Comment by NoahDragon** [comment]
@noraj1337 I'm not sure, because I couldn't reproduce this issue, and I'm using the marked renderer.

**Comment by noraj1337** [comment]
@NoahDragon I tried again. The html content generated by markdown it is good. But even with fancybox set to False, there is some javascript dynamically adding a fancybox class and changing the href. 

At the end of each page there is

```html
<script src="/js/script.js"></script>
```

This script contain:

```js
[...]
// Caption
  $('.article-entry').each(function(i){
    $(this).find('img').each(function(){
      if ($(this).parent().hasClass('fancybox')) return;

      var alt = this.alt;

      if (alt) $(this).after('<span class="caption">' + alt + '</span>');

      $(this).wrap('<a href="' + this.src + '" title="' + alt + '" class="fancybox"></a>');
    });

    $(this).find('.fancybox').each(function(){
      $(this).attr('rel', 'article' + i);
    });
  });

  if ($.fancybox){
    $('.fancybox').fancybox();
  }
[...]
```

**Comment by noraj1337** [comment]
The ejs template including the script is `themes/landscape/layout/_partial/after-footer.ejs`.

Where you can see:

```ejs
[...]
<% if (theme.fancybox){ %>
  <%- css('fancybox/jquery.fancybox') %>
  <%- js('fancybox/jquery.fancybox.pack') %>
<% } %>

<%- js('js/script') %>
```

So `<%- js('js/script') %>` is included even if theme.fancybox is false and that script is generating the problem.

**Comment by noraj1337** [comment]
Issue open https://github.com/hexojs/hexo-theme-landscape/issues/96

**Comment by noraj1337** [comment]
We can close it here.
