### ISSUE TITLE
 Cannot find module 'highlight.js'

### ISSUE THREAD

**Issue by Lyuke-liu** [hexojs/hexo-renderer-markdown-it#47]
I used the commond "hexo clean",then 
![markdown_it-error](https://user-images.githubusercontent.com/24935256/29240250-c5597092-7f93-11e7-95d1-5df07afbd7b5.png)

**Comment by noraj1337** [comment]
@Lyuke-liu You opened the issue on the wrong repository.

Open it here https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus

**Comment by noraj** [comment]
@SukkaW We may close this issue.

**Comment by SukkaW** [comment]
@noraj Sounds like a good idea. I will close this PR then.

**Comment by noraj** [comment]
@SukkaW Totally unrelated: I want to be a hexo org member, I send a mail to address suggested in hexo site PR template but never got an answer.
