### ISSUE TITLE
Table code blocks in hexo

### ISSUE THREAD

**Issue by muwednesday** [hexojs/hexo-renderer-markdown-it#50]
I have written  markdown syntax tutorials in my GitHub pages using hexo. When I wrote code blocks of table, hexo rendered them as real table. Please help.
The following are codes from [markdown-down.js](https://github.com/markdown-it/markdown-it/blob/master/dist/markdown-it.js#L3998)
```javascript
// if it's indented more than 3 spaces, it should be a code block
if (state.sCount[nextLine] - state.blkIndent >= 4) { return false; }
```

**Comment by muwednesday** [comment]
I solved this problem by installing the latest version of hexo-renderer-markdown-it(3.4.2):
```
npm install https://github.com/hexojs/hexo-renderer-markdown-it
```
But the npm latest version is 3.4.1, please update it.

**Comment by stevenjoezhang** [comment]
New version released: https://www.npmjs.com/package/hexo-renderer-markdown-it
