### ISSUE TITLE
Extra space with 'default' caused by line breaks=false

### ISSUE THREAD

**Issue by yzlnew** [hexojs/hexo-renderer-markdown-it#51]
![2017-12-15 8 21 36](https://user-images.githubusercontent.com/4904877/34041997-a0fd9e7c-e1d5-11e7-801d-71d82e768910.png)

Using either marked  or markdown-it with `breaks=false`, and writing markdown files with paragraphs of multi lines causes this issue.

**Comment by curbengh** [comment]
``` js
const md = require('markdown-it')({
  breaks: false
})

console.log(md.render('lorem\nlorem\nlorem'))
```

``` html
<p>lorem
lorem
lorem</p>
```

Newline `\n` is displayed as a space in browser.
