### ISSUE TITLE
add support for all external markdown-it plugins

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo-renderer-markdown-it#53]
Is it possible to add support for all external markdown-it plugins ?

[hexo-renderer-markdown-it-plus](https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus#add-other-markdown-it-plugins) seems to do something like that.

**Comment by noraj** [comment]
I may not have expressed myself well, [markdown-it](https://github.com/markdown-it/markdown-it) can work with

> Community-written [plugins](https://www.npmjs.org/browse/keyword/markdown-it-plugin) and [other packages](https://www.npmjs.org/browse/keyword/markdown-it) on npm.

So hexo-renderer-markdown-it should work with them too. Of course hexo-renderer-markdown-it should not provide support for bugs that may happen with the external plugins. hexo-renderer-markdown-it should just enable a way to work with them so people can fend for themselves. Exactly like markdown-it is doing.

PS : as I said in #55 I'm looking for TOC support, but hexo-renderer-markdown-it-plus is really buggy and so are markdown-it-toc-and-anchor and markdown-it-toc. So if a plugin capability is added I would be able to try with some [other plugins](https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus/issues/13#issuecomment-388144623).

**Comment by curbengh** [comment]
once a plugin is installed, it can be enabled through the [`plugins`](https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration#plugins) option.
