### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo-renderer-markdown-it#54]
This change (commit https://github.com/hexojs/hexo-renderer-markdown-it/commit/7e15bb7ac4aef7552db1bc0d08ba689808ec2825) `now support all markdown-it official plugins` but the README and the wiki weren't changed.

**Comment by noraj** [comment]
Bump

```
    case: 0
    separator: ''
```

Those two config options are not mentioned in https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration

**Comment by curbengh** [comment]
> This change (commit [7e15bb7](https://github.com/hexojs/hexo-renderer-markdown-it/commit/7e15bb7ac4aef7552db1bc0d08ba689808ec2825)) `now support all markdown-it official plugins` but the README and the wiki weren't changed.

https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration/_compare/20eb8c299eee074cb6d36d5f5b6bc2d2697d8128...299166a176ba3962c1ec2f7b8c1baad7e1052167

> Those two config options are not mentioned in https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration

https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration/_compare/299166a176ba3962c1ec2f7b8c1baad7e1052167...d55b3aebeb36ee9b6c2c0cc7ac01316d2d177122
