### ISSUE TITLE
Why instantiate a new markdown renderer for each file processed?

### ISSUE THREAD

**Issue by oravecz** [hexojs/hexo-renderer-markdown-it#57]
I assume the rendering process would execute much faster if the Markdown parser was configured once, then used repeatedly. Currently, for each file processed, the renderer is instantiated, all the plugins loaded, and configured, and finally, the text is processed.

Is there a reason for this? Perhaps the plugins or the markdown renderer is stateful?

**Comment by curbengh** [comment]
May I know what did you change to make this renderer only instantiate once?

**Comment by SukkaW** [comment]
> May I know what did you change to make this renderer only instantiate once?

@curbengh As you can see, we require `markdown-it` whenever the renderer function is called:

https://github.com/hexojs/hexo-renderer-markdown-it/blob/a4f2be73b93598f9931a8db2a335719c35bb8921/lib/renderer.js#L4

We also `new` a `markdown-it` instance whenever the renderer function is called:

https://github.com/hexojs/hexo-renderer-markdown-it/blob/a4f2be73b93598f9931a8db2a335719c35bb8921/lib/renderer.js#L16

We could improve the performance by only require and `new` the markdown-it instance once.
