### ISSUE TITLE
Whether plug-in custom parameters are supported

### ISSUE THREAD

**Issue by suxin2017** [hexojs/hexo-renderer-markdown-it#85]
Some plugins can't take effect because they can't pass custom parameters.
 Can you add custom parameters? 😊

**Comment by EriKWDev** [comment]
Already an open issue, but I agree.
upvote [issue 58](https://github.com/hexojs/hexo-renderer-markdown-it/issues/58 ) and let's hope for the best ^^
Would be awesome to have markdown-it-container support.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-renderer-markdown-it/issues/58

**Comment by curbengh** [comment]
Except for function, you can specify custom options to a plugin, see [guide](https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration#plugin-option). For function, you need [this approach](https://github.com/hexojs/hexo-renderer-markdown-it#extensibility) instead.
