### ISSUE TITLE
hexo-renderer-markdown-it doesn't work and told me " Package hexo-renderer-marked is not installed."

### ISSUE THREAD

**Issue by tsotfsk** [hexojs/hexo-renderer-markdown-it#98]
my theme is icarus 
 
INFO  Checking dependencies
ERROR Package hexo-renderer-marked is not installed.
ERROR Please install the missing dependencies from the root directory of your Hexo site.

**Comment by SukkaW** [comment]
It is not the issue of `hexo-theme-markdown-it`.

It seems that icarus theme requires you using `hexo-renderer-marked` instead of `hexo-theme-markdown-it`. Please ask your theme maintainer (@ppoffice) for assistance.
